# Generated by Django 4.1.7 on 2023-03-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_stocks_user_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stocks',
        ),
        migrations.AddField(
            model_name='user',
            name='stocks',
            field=models.ManyToManyField(to='api.stock'),
        ),
    ]
