# Generated by Django 4.1.7 on 2023-04-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_stocks_user_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='money_current',
            new_name='money_spent',
        ),
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
