# Generated by Django 4.1.7 on 2023-04-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_money_current_user_money_spent_userstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
