# Generated by Django 4.1.7 on 2023-04-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='api.stock'),
        ),
    ]
