# Generated by Django 4.1.7 on 2023-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_money_spent_alter_user_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstocks',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
