# Generated by Django 4.1.7 on 2023-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userstocks_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
