# Generated by Django 4.1.7 on 2023-04-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stock_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='shares',
        ),
    ]
