# Generated by Django 4.1.7 on 2023-05-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userstock_remove_stock_shares_delete_userstocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
