# Generated by Django 4.1.7 on 2023-05-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userstock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='stock',
            field=models.CharField(max_length=5),
        ),
    ]
